from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('accounts/register/', views.registration, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.employee_create, name='employee_create'),
    path('employees/<int:pk>/', views.employee_detail, name='employee_detail'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee_edit'),
    path('employees/<int:pk>/deactivate/', views.employee_deactivate, name='employee_deactivate'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.department_create, name='department_create'),
    path('departments/<int:pk>/', views.department_detail, name='department_detail'),
    path('departments/<int:pk>/edit/', views.department_edit, name='department_edit'),
    path('shifts/', views.shift_list, name='shift_list'),
    path('shifts/add/', views.shift_create, name='shift_create'),
    path('shifts/<int:pk>/', views.shift_detail, name='shift_detail'),
    path('shifts/<int:pk>/edit/', views.shift_edit, name='shift_edit'),
    path('attendance/', views.attendance_today, name='attendance_today'),
    path('attendance/check-in/', views.attendance_check_in, name='attendance_check_in'),
    path('attendance/check-out/', views.attendance_check_out, name='attendance_check_out'),
    path('reports/', views.reports, name='reports'),
    path('reports/export/', views.reports_export_csv, name='reports_export_csv'),
    path('payroll/', views.payroll_summary, name='payroll_summary'),
    path('holidays/', views.holiday_list, name='holiday_list'),
    path('holidays/add/', views.holiday_create, name='holiday_create'),
    path('overtime/', views.overtime_list, name='overtime_list'),
    path('overtime/add/', views.overtime_request_create, name='overtime_request_create'),
    path('overtime/<int:pk>/approve/', views.overtime_approve, name='overtime_approve'),
    path('overtime/<int:pk>/reject/', views.overtime_reject, name='overtime_reject'),
    path('users/', views.user_management, name='user_management'),
    path('users/<int:pk>/approve/', views.approve_user, name='approve_user'),
    path('audit-logs/', views.audit_log_list, name='audit_log_list'),
    path('leaves/', views.leave_list, name='leave_list'),
    path('leaves/add/', views.leave_request_create, name='leave_request_create'),
    path('leaves/<int:pk>/approve/', views.leave_approve, name='leave_approve'),
    path('leaves/<int:pk>/reject/', views.leave_reject, name='leave_reject'),
    path('leaves/<int:pk>/cancel/', views.leave_cancel, name='leave_cancel'),
]
