# Generated by Django 5.2.17 on 2026-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_device',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_status',
            field=models.CharField(choices=[('Not Enrolled', 'Not Enrolled'), ('Pending', 'Pending'), ('Enrolled', 'Enrolled')], default='Not Enrolled', max_length=20),
        ),
    ]
