# Generated by Django 5.2.17 on 2026-10-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_payrollrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
